<?php
/**
 * Copyright (c) 2019.
 * Author:Alone88
 * Github:https://github.com/anhao
 */

namespace app\admin\extend;


use think\paginator\driver\Bootstrap;

class Page extends Bootstrap
{
    /**
     *  上一页按钮
     * @param string $text
     * @return string
     */
    protected function getPreviousButton($text = "上一页")
    {
        return parent::getPreviousButton($text); // TODO: Change the autogenerated stub
    }

    /** 下一页按钮
     * @param string $text
     * @return string
     */
    protected function getNextButton($text = '下一页')
    {
        return parent::getNextButton($text); // TODO: Change the autogenerated stub
    }

    protected function getLinks()
    {
        return parent::getLinks(); // TODO: Change the autogenerated stub
    }

    public function render()
    {
        return parent::render(); // TODO: Change the autogenerated stub
    }

    /** 生成一个激活的按钮
     * @param string $text
     * @return string
     */
    protected function getActivePageWrapper($text)
    {
        return '<li class="page-item active"><span class="page-link">' . $text . '</span></li>';
    }

    /** 生成一个可点击的按钮
     * @param string $url
     * @param int $page
     * @return string
     */
    protected function getAvailablePageWrapper($url, $page)
    {
        return '<li class="page-item"><a class="page-link" href="' . htmlentities($url) . '">' . $page . '</a></li>';
    }

    /**
     * 生成一个禁用的按钮
     * @param string $text
     * @return string
     */
    protected function getDisabledTextWrapper($text)
    {
        return '<li class="page-item  disabled"><span class="page-link">' . $text . '</span></li>';
    }
}